# Generated by Django 2.2.5 on 2021-03-22 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='论文标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='研究主题')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
            },
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='姓名')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.Topic', verbose_name='研究主题')),
            ],
            options={
                'verbose_name': '上传者',
                'verbose_name_plural': '上传者',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='论文题目')),
                ('review', models.TextField(verbose_name='论文总结')),
                ('researcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='papers.Researcher', verbose_name='上传人')),
                ('tag', models.ManyToManyField(to='papers.Tag', verbose_name='论文标签')),
            ],
            options={
                'verbose_name': '论文',
                'verbose_name_plural': '论文',
                'ordering': ['title'],
            },
        ),
    ]
